const questionList = [
    "What is your primary love language? Acts of Service, Words of Affirmation, Receiving Gifts, Quality Time, or Physical Touch?",
    "How do you like to receive Words of Affirmation? Is there a specific way or frequency that makes you feel loved and appreciated?",
    "In what ways do you enjoy showing Acts of Service to your partner? What tasks or actions make you feel most connected?",
    "Is there a specific gesture or action that always makes you feel loved, regardless of your primary love language?",
    "How do you like to communicate your love for your partner? Are there specific phrases or actions that resonate with you?",
    "What are some ways you enjoy spending Quality Time together?",
    "How important is Physical Touch in maintaining a sense of connection and intimacy for you?",
    "What is your favorite childhood memory? Can you share the story behind it?",
    "What was your favorite game or activity to play as a child? Do you still enjoy it today?",
    "What was your favorite book or movie during your childhood? Did it have a significant impact on you?",
    "Did you have any unique or interesting traditions in your family when you were growing up?",
    "What was your favorite place to visit or vacation during your childhood? Why was it special to you?",
    "Did you have any hobbies or interests as a child that you still pursue today?",
    "Is there a particular lesson or piece of advice from your childhood that has stuck with you throughout your life?",
    "What was your favorite subject or class in school during your childhood? Why did you enjoy it?",
    "Were there any challenges or hardships you faced during your childhood that have shaped who you are today?",
    "Did you have any role models or people who influenced you greatly during your childhood? How did they impact your life?",
    "What are you looking for in a new relationship?",
    "What are your top priorities and non-negotiables in a partner?",
    "What is your love language, and how can I make you feel loved and appreciated?",
    "What are your goals and aspirations for the future, and how do you envision a partner fitting into them?",
    "What are your expectations when it comes to communication and spending time together?",
    "What do you value most in a romantic relationship, and how do you show it?",
    "What are your thoughts on commitment and exclusivity?",
    "How do you navigate and resolve conflicts in a relationship?",
    "What are your boundaries and needs when it comes to personal space and alone time?",
    "What are some of your past relationship experiences, and what have you learned from them?",
    "Do you envision yourself having children in the future?",
    "What are your thoughts on the ideal timing for starting a family?",
    "How many children, if any, do you see yourself wanting?",
    "What are your expectations regarding parenting roles and responsibilities?",
    "What values and principles would you like to instill in your children?",
    "How do you envision balancing career and family life?",
    "What kind of support system do you envision having in place when raising children?",
    "What are your thoughts on discipline and guiding children's behavior?",
    "How do you feel about the possibility of adopting or fostering children?",
    "What are your hopes and dreams for your future family?",
    "What is your dream travel destination, and why does it captivate you?",
    "Do you prefer adventurous, off-the-beaten-path travel or relaxing, luxurious vacations?",
    "Is there a specific travel experience or activity that you've always wanted to try?",
    "What are your thoughts on solo travel versus traveling as a couple or with a group?",
    "Are there any countries or cultures you're particularly interested in exploring?",
    "What is your favorite travel memory or the most memorable trip you've taken?",
    "Do you prefer to meticulously plan every aspect of a trip or leave room for spontaneity?",
    "What is your favorite mode of transportation when traveling: plane, train, car, or something else?",
    "Are there any travel traditions or rituals you enjoy when exploring new places?",
    "How do you feel about immersing yourself in the local culture and trying new foods when traveling?",
    "What is your favorite sport to watch or play? Why?",
    "Do you have a favorite sports team? If so, which one and why are you a fan?",
    "Have you ever played any sports competitively? If so, which ones and what was your experience like?",
    "Do you enjoy participating in sports or prefer being a spectator?",
    "What sports-related hobbies or activities do you enjoy outside of watching or playing?",
    "Are there any sports events or tournaments you would love to attend in person?",
    "Do you have a favorite athlete or sports role model? Who inspires you in the world of sports?",
    "What is your favorite sports-related memory or moment?",
    "Do you enjoy sports-related fitness activities, such as running, swimming, or cycling?",
    "How do you feel about the influence of sports in society, including its impact on culture and values?",
    "What is your favorite way to relax and unwind?",
    "If you could have any superpower, what would it be and why?",
    "What is your go-to comfort food or guilty pleasure?",
    "If you could travel back in time, which era would you choose to visit and why?",
    "What is one thing on your bucket list that you are determined to accomplish?",
    "If you could have dinner with any historical figure, who would you choose and why?",
    "What is your favorite hobby or pastime outside of work or studies?",
    "If you could learn any new skill instantly, what would it be and why?",
    "What is the most memorable concert or live performance you have ever attended?",
    "If you had a free day with no obligations, how would you choose to spend it?",
    "Marvel or DC?",
    "Do you believe in absolute moral values, or do you think ethics are relative and context-dependent?",
    "How do you approach ethical dilemmas or difficult moral decisions?",
    "Are there any ethical principles or philosophies that you strongly identify with?",
    "How important is honesty and transparency in your personal and professional life?",
    "How do you navigate ethical conflicts between personal values and societal norms or expectations?",
    "If you could have any fictional character as your best friend, who would it be and why?",
    "What is your favorite movie quote or line that you find yourself quoting often?",
    "If you could instantly become an expert in any skill or subject, what would it be?",
    "What is the most adventurous thing you have ever done or would like to do?",
    "If you were stranded on a deserted island, what three things would you want to have with you?",
    "What is your favorite ice cream flavor, and what toppings do you like on it?",
    "If you could time travel, would you go to the past or the future? Why?",
    "What is your favorite board game or card game, and why do you enjoy playing it?",
    "If you could trade places with any celebrity for a day, who would it be and why?",
    "What is your favorite joke or funny anecdote that always makes you laugh?"
];

export default questionList;